export type RecPojam = {
  word: string;
  image?: string;
  emoji: string;
};

export const SASTAVI_RECI: RecPojam[] = [
  { word: "ПАС", image: "/slike/azbuka/pas.jpeg", emoji: "🐶" },
  { word: "МИШ", emoji: "🐭" },
  { word: "СИР", emoji: "🧀" },
  { word: "ЦРВ", emoji: "🪱" },
  { word: "ПУЖ", emoji: "🐌" },
  { word: "ЗЕЦ", emoji: "🐰" },
  { word: "ЛАВ", image: "/slike/azbuka/lav.jpeg", emoji: "🦁" },
  { word: "ВОЗ", emoji: "🚂" },
  { word: "ОКО", image: "/slike/azbuka/oko.jpeg", emoji: "👁️" },
  { word: "УВО", image: "/slike/azbuka/uvo.jpeg", emoji: "👂" },
  { word: "НОС", image: "/slike/azbuka/nos.jpeg", emoji: "👃" },
  { word: "ЗУБ", emoji: "🦷" },
  { word: "МЕД", emoji: "🍯" },
  { word: "ЛЕД", emoji: "🧊" },
  { word: "СОК", emoji: "🧃" },
  { word: "САТ", emoji: "🕐" },
  { word: "СТО", emoji: "🪑" },
  { word: "ШАЛ", emoji: "🧣" },
  { word: "ЂАК", image: "/slike/azbuka/djak.jpeg", emoji: "🎒" },
  { word: "КОЊ", emoji: "🐴" },
  { word: "ЈЕЖ", emoji: "🦔" },
  { word: "МАЦА", image: "/slike/azbuka/macka.jpeg", emoji: "🐱" },
  { word: "АУТО", image: "/slike/car.jpeg", emoji: "🚗" },
  { word: "БРОД", emoji: "🚢" },
  { word: "ВОДА", emoji: "💧" },
  { word: "ДРВО", image: "/slike/azbuka/drvo.jpeg", emoji: "🌳" },
  { word: "ЖАБА", emoji: "🐸" },
  { word: "ЗМАЈ", emoji: "🐉" },
  { word: "КАПА", emoji: "🧢" },
  { word: "КОЗА", emoji: "🐐" },
  { word: "КУЋА", emoji: "🏠" },
  { word: "ЛИСТ", emoji: "🍃" },
  { word: "МЕДА", emoji: "🧸" },
  { word: "НЕБО", emoji: "☁️" },
  { word: "ОВЦА", emoji: "🐑" },
  { word: "ПАРК", emoji: "🛝" },
  { word: "РИБА", image: "/slike/azbuka/riba.jpeg", emoji: "🐟" },
  { word: "РОДА", emoji: "🐦" },
  { word: "СЛОН", emoji: "🐘" },
  { word: "СОВА", emoji: "🦉" },
  { word: "ЦВЕТ", image: "/slike/azbuka/cvet.jpeg", emoji: "🌸" },
  { word: "ХЛЕБ", image: "/slike/azbuka/hleb.jpeg", emoji: "🍞" },
  { word: "ШУМА", emoji: "🌲" },
  { word: "ВРАТА", emoji: "🚪" },
  { word: "КЛУПА", emoji: "🪑" },
  { word: "КЊИГА", image: "/slike/azbuka/knjiga.jpeg", emoji: "📚" },
  { word: "КРАВА", emoji: "🐄" },
  { word: "ЛОПТА", image: "/slike/azbuka/fudbal.jpeg", emoji: "⚽" },
  { word: "МЕСЕЦ", emoji: "🌙" },
  { word: "ПАТКА", emoji: "🦆" },
  { word: "ПЕТАО", emoji: "🐓" },
  { word: "ПТИЦА", emoji: "🐦" },
  { word: "СУНЦЕ", image: "/slike/azbuka/sunce.jpeg", emoji: "☀️" },
  { word: "ТИГАР", emoji: "🐯" },
  { word: "ТОРТА", image: "/slike/azbuka/torta.jpeg", emoji: "🎂" },
];
